### ISSUE TITLE
Corrections IMHO

### ISSUE THREAD

**Issue by Efesto** [mircoporetti/resume#1]
the last sentence here you can skip -> https://github.com/mircoporetti/resume/blob/4a6feea15d81cdcc610d7cec0555f83b6b1bf1d4/main.tex#L124

This you can skip, sounds a bit like a duplication -> 
https://github.com/mircoporetti/resume/blob/main/main.tex#L88

The comma in this sentence can be removed -> 
https://github.com/mircoporetti/resume/blob/main/main.tex#L144

`Review` or `Code review` and `Communication` as a buzzwords don't tell much, would be more interesting something describing you, like `backend` or `frontend` or something like that

All of this, IMHO :D

**Comment by mircoporetti** [comment]
Thanks man for your suggestions :)

**Comment by mircoporetti** [comment]
> the last sentence here you can skip ->
> 
> https://github.com/mircoporetti/resume/blob/4a6feea15d81cdcc610d7cec0555f83b6b1bf1d4/main.tex#L124
> 
> This you can skip, sounds a bit like a duplication ->
> https://github.com/mircoporetti/resume/blob/main/main.tex#L88
> 
> The comma in this sentence can be removed ->
> https://github.com/mircoporetti/resume/blob/main/main.tex#L144
> 
> `Review` or `Code review` and `Communication` as a buzzwords don't tell much, would be more interesting something describing you, like `backend` or `frontend` or something like that
> 
> All of this, IMHO :D

Thanks man for your suggestions, I found them reasonable and I did some change :)
